Create Desktop version using media queries on mobile version of project
fibini/Portfolio-project pull request #4
Opened 2022-04-28 23:19 UTC by fibini

Used media queries on mobile version to create the Desktop version, changed and added code to index.html and css files

2022-04-28 23:36 UTC, youmari requested changes
Hi <STUDENT_MENTION>, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights

✔️ Great Design implementation
✔️No linter error
✔️ Descriptive PR


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-28 23:36 UTC, youmari commented on index.html
>          <img
Nice implementing the design, however, you should add some padding with an 804px widescreen so the left side will be the same as the right side 
![image](https://user-images.githubusercontent.com/61790587/165863851-50fc6c94-cddf-4be3-a8a5-53ef7aade05b.png)

2022-04-28 23:36 UTC, youmari commented on index.html
>          <div class="socials">
please try to remove the yellow color when hovering on the links 
![image](https://user-images.githubusercontent.com/61790587/165864156-9e9b30dd-8ee2-4e9f-9718-7aba3544f073.png)

2022-04-29 00:30 UTC, fibini commented
Made recommended changes to project, added padding to middle section and removed yellow hover effect from social icons

2022-04-29 00:39 UTC, OLIPLICHE approved these changes
Hi @fibini , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-29 01:06 UTC, merged